name: 'Run Spring App Advisor'
description: 'Runs Spring Application Advisor against the project'

inputs:
  spring-enterprise-token:
    description: 'A token with permissions to download Spring App Advisor and authenticate to the recipe repository'
    required: true
  spring-enterprise-username:
    description: 'The repository username'
    required: true

  advisor-version:
    description: 'The version of Spring App Advisor to use'
    required: false
    default: '1.5.2'
  directory:
    description: 'The directory in the project to analyze; defaults to the root of the project'
    required: false
    default: '.'
  spring-enterprise-repository:
    description: 'The repository containing the Spring App Advisor recipes'
    required: false
    default: 'https://packages.broadcom.com/artifactor/spring-enterprise'

runs:
  using: 'composite'
  steps:
  - id: download-advisor
    name: "Download Advisor ${{ inputs.advisor-version }}"
    shell: bash
    env:
      ADVISOR_TOKEN: ${{ inputs.spring-enterprise-token }}
      ADVISOR_VERSION: ${{ inputs.advisor-version }}
    run: |
      curl -v -L -H "Authorization: Bearer $ADVISOR_TOKEN" -o advisor-cli.tar "https://packages.broadcom.com/artifactory/spring-enterprise/com/vmware/tanzu/spring/application-advisor-cli-linux/${ADVISOR_VERSION}/application-advisor-cli-linux-${ADVISOR_VERSION}.tar"
      tar -xf advisor-cli.tar --strip-components=1 --exclude=./META-INF
  - id: create-settings-xml
    shell: bash
    env:
      URL: ${{ inputs.spring-enterprise-repository }}
      USERNAME: ${{ inputs.spring-enterprise-username }}
      PASSWORD: ${{ inputs.spring-enterprise-token }}
    run: |
      sed -e "s/__SPRING_ENTERPRISE_REPOSITORY_URL__/${URL}/g" -e "s/__SPRING_ENTERPRISE_REPOSITORY_USERNAME__/${USERNAME}/g" -e "s/__SPRING_ENTERPRISE_REPOSITORY_PASSWORD/${PASSWORD}/g" settings.xml.template > $HOME/.m2/settings.xml
  - id: run-advisor-maven
    shell: bash
    env:
      DIRECTORY: ${{ inputs.directory }}
      GIT_TOKEN_FOR_PRS: ${{ github.token }}
    run: |
      advisor build-config get -b=mvnw -p=${DIRECTORY}
      advisor upgrade-plan apply --push --from-yml
  - id: create-init-gradle
    shell: bash
    env:
      URL: ${{ inputs.spring-enterprise-repository }}
      USERNAME: ${{ inputs.spring-enterprise-username }}
      PASSWORD: ${{ inputs.spring-enterprise-token }}
    run: |
      sed -e "s/__SPRING_ENTERPRISE_REPOSITORY_URL__/${URL}/g" -e "s/__SPRING_ENTERPRISE_REPOSITORY_USERNAME__/${USERNAME}/g" -e "s/__SPRING_ENTERPRISE_REPOSITORY_PASSWORD/${PASSWORD}/g" init.gradle.template > $HOME/.gradle/init.gradle
  - id: run-advisor-gradle
    shell: bash
    env:
      DIRECTORY: ${{ inputs.directory }}
      GIT_TOKEN_FOR_PRS: ${{ github.token }}
    run: |
      advisor build-config get -b=gradlew -p=${DIRECTORY}
      advisor upgrade-plan apply --push --from-yml