name: 'Run Spring App Advisor'
description: 'Runs Spring Application Advisor against the project'

inputs:
  spring-enterprise-token:
    description: 'A token with permissions to download Spring App Advisor and authenticate to the recipe repository'
    required: true
  spring-enterprise-username:
    description: 'The repository username'
    required: true

  advisor-version:
    description: 'The version of Spring App Advisor to use'
    required: false
    default: '1.5.2'
  directory:
    description: 'The directory in the project to analyze; defaults to the root of the project'
    required: false
    default: '.'
  spring-enterprise-repository:
    description: 'The repository containing the Spring App Advisor recipes'
    required: false
    default: 'https://packages.broadcom.com/artifactory/spring-enterprise'

runs:
  using: 'composite'
  steps:
  - id: download-advisor
    name: "Download Advisor ${{ inputs.advisor-version }}"
    shell: bash
    env:
      ADVISOR_TOKEN: ${{ inputs.spring-enterprise-token }}
      ADVISOR_VERSION: ${{ inputs.advisor-version }}
      ADVISOR_REPOSITORY: ${{ inputs.spring-enterprise-repository }}
    run: |
      curl -L -H "Authorization: Bearer $ADVISOR_TOKEN" -o advisor-cli.tar "${ADVISOR_REPOSITORY}/com/vmware/tanzu/spring/application-advisor-cli-linux/${ADVISOR_VERSION}/application-advisor-cli-linux-${ADVISOR_VERSION}.tar"
      tar -xf advisor-cli.tar --strip-components=1 --exclude=./META-INF
  - uses: actions/setup-java@v5.1.0
    with:
      java-version: 17
      distribution: temurin
  - id: copy-maven-settings
    shell: bash
    run: |
      mkdir -p "$HOME/.m2"
      cp "$GITHUB_ACTION_PATH/settings.xml" "$HOME/.m2/settings.xml"
  - id: run-advisor-maven
    shell: bash
    env:
      DIRECTORY: ${{ inputs.directory }}
      GIT_TOKEN_FOR_PRS: ${{ github.token }}
      SPRING_ENTERPRISE_REPOSITORY_URL: ${{ inputs.spring-enterprise-repository }}
      SPRING_ENTERPRISE_REPOSITORY_USERNAME: ${{ inputs.spring-enterprise-username }}
      SPRING_ENTERPRISE_REPOSITORY_PASSWORD: ${{ inputs.spring-enterprise-token }}
    run: |
      cd $HOME/${DIRECTORY}
      ./advisor build-config get -b=mvnw -d
      ./advisor upgrade-plan apply -b=mvnw -d --push --from-yml 
  - uses: spring-io/spring-gradle-build-action@v2
    with:
      java-version: 17
      distribution: temurin
  - id: copy-gradle-settings
    shell: bash
    run: |
      mkdir -p "$HOME/.gradle"
      cp "$GITHUB_ACTION_PATH/init.gradle" "$HOME/.gradle/init.gradle"
  - id: run-advisor-gradle
    shell: bash
    env:
      DIRECTORY: ${{ inputs.directory }}
      GIT_TOKEN_FOR_PRS: ${{ github.token }}
      SPRING_ENTERPRISE_REPOSITORY_URL: ${{ inputs.spring-enterprise-repository }}
      SPRING_ENTERPRISE_REPOSITORY_USERNAME: ${{ inputs.spring-enterprise-username }}
      SPRING_ENTERPRISE_REPOSITORY_PASSWORD: ${{ inputs.spring-enterprise-token }}
    run: |
      cd $HOME/${DIRECTORY}
      ./advisor build-config get -b=gradlew -d
      ./advisor upgrade-plan apply -b=gradlew -d --push --from-yml
  - id: show-advisor-errors
    if: failure()
    shell: bash
    env:
      DIRECTORY: ${{ inputs.directory }}
    run: |
      shopt -s nullglob
      logs=($DIRECTORY/.advisor/errors/*.log)
      if [ ${#logs[@]} -eq 0 ]; then
        echo "No advisor error logs found."
        exit 0
      fi

      for f in "${logs[@]}"; do
        echo "----- BEGIN $f -----"
        cat "$f"
        echo "----- END $f -----"
      done