name: 'Generate GitHub App Token'
description: 'Generates a GitHub App token'
inputs:
  app_id:
    description: 'The ID of the GitHub App'
    required: true
  private_key:
    description: 'The private key of the GitHub App'
    required: true
outputs:
  token:
    description: 'The generated GitHub App token'
runs:
  using: 'node16'
  main: 'index.js'
